services:
  stats-server:
    build: stats/server
    image: ewm-stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  ewm-service:
    build: ewm
    image: ewm-main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres